### ISSUE TITLE
请教一下，你是如何编译出来带bitcode版本的framework的呢？

### ISSUE THREAD

**Issue by coder-free** [hello-david/SwiftV2Ray#10]
请教一下，你是如何编译出来带bitcode版本的framework的呢？
我用的这个 https://github.com/xxf098/go-tun2socks-build 里面的方式，编译出来不带 bitcode

**Comment by hello-david** [comment]
貌似gomobile就没支持bitcode

Binfeng Zhang <notifications@github.com> 于2020年3月29日周日 下午2:00写道：
