### ISSUE TITLE
PacketTunnel 超过15MB崩溃掉线

### ISSUE THREAD

**Issue by CNKCQ** [hello-david/SwiftV2Ray#25]
PacketTunnel 超过 15MB 崩溃掉线，大佬，这个问题又解决么 tun2socks 是如何编译的呢？

**Comment by Cyberbolt** [comment]
请问解决了吗？我也是，2024 年了，iOS 17.3.1 仍然是 NE 超过 15 MB 断连，并不像网上提到的 50 MB。

![ios17NE测试图](https://p2-img.bug.im/202402/13a8d6db34e8d.png)
