### ISSUE TITLE
编译了工程到手机，可以添加节点（wmess订阅链接），点击“🔗”按钮，但未能启动vpn

### ISSUE THREAD

**Issue by wansellbusiness** [hello-david/SwiftV2Ray#3]

**Comment by hello-david** [comment]
不清楚是不是越狱机器VPN配置未生效的问题，我在添加完配置后重新reboot一下机器再点击开关按钮是可以连接上的
![-w120](https://user-images.githubusercontent.com/17873903/74794532-66515b00-52fe-11ea-9e96-91237a3f3ab9.png)

**Comment by wangjinwei0806** [comment]
我有测试能启动VPN的，但是链接之后 访问Google 打不开，还有YouTube也是这样的

**Comment by wangjinwei0806** [comment]
![image](https://user-images.githubusercontent.com/3974508/74829586-4e082d00-534c-11ea-9172-eff9ce579bbb.png)

**Comment by hello-david** [comment]
在Xcode->debug->Attach to Process by ID or name里面可以进行调试PacketTunel的调试 ![picture](https://user-images.githubusercontent.com/17873903/74891944-4172eb80-53c3-11ea-9939-5322bde85cea.png)，确认一下项目内置的config是否符合你的服务端要求

**Comment by wangjinwei0806** [comment]
这里调试我知道，你的通道开启的时候存在逻辑问题，也就是代理软件如果你之前使用了其它的话，不能正常切换的

**Comment by wangjinwei0806** [comment]
![image](https://user-images.githubusercontent.com/3974508/74892821-a6c7dc00-53c5-11ea-8d72-9d1c8528b7ee.png)


{
    "outbounds":[
        {
            "mux":{
                "enabled":false,
                "concurrency":8
            },
            "protocol":"vmess",
            "streamSettings":{
                "tcpSettings":{
                    "header":{
                        "type":"none"
                    }
                },
                "tlsSettings":{
                    "allowInsecure":false
                },
                "security":"none",
                "network":"tcp"
            },
            "tag":"direct",
            "settings":{
                "vnext":[
                    {
                        "address":"xxxxxxx",
                        "users":[
                            {
                                "id":"xxxxdaa0",
                                "alterId":233,
                                "level":2,
                                "security":"none"
                            }
                        ],
                        "port":11111
                    }
                ]
            }
        }
    ]
}

**Comment by wansellbusiness** [comment]
我在调试时出现appex 15M内存限制导致vpn进程被系统kill掉的情况，请问您是如何解决？

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: wangjinwei0806 <notifications@github.com>
发送时间: Thursday, February 20, 2020 9:45:44 AM
收件人: hello-david/SwiftV2Ray <SwiftV2Ray@noreply.github.com>
抄送: wansellbusiness <wansellbusiness@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [hello-david/SwiftV2Ray] 编译了工程到手机，可以添加节点（wmess订阅链接），点击“🔗”按钮，但未能启动vpn (#3)


[image]<https://user-images.githubusercontent.com/3974508/74892821-a6c7dc00-53c5-11ea-8d72-9d1c8528b7ee.png>

{
"outbounds":[
{
"mux":{
"enabled":false,
"concurrency":8
},
"protocol":"vmess",
"streamSettings":{
"tcpSettings":{
"header":{
"type":"none"
}
},
"tlsSettings":{
"allowInsecure":false
},
"security":"none",
"network":"tcp"
},
"tag":"direct",
"settings":{
"vnext":[
{
"address":"xxxxxxx",
"users":[
{
"id":"xxxxdaa0",
"alterId":233,
"level":2,
"security":"none"
}
],
"port":11111
}
]
}
}
]
}

**Comment by coder-free** [comment]
![image](https://user-images.githubusercontent.com/2630290/77840970-7e4eb100-71bf-11ea-9cec-a636057c48bf.png)
刚启动啥都还没干呢，直接就13.6M了。。。数据还怎么传。。。内存里都放了些啥啊。。go语言一窍不通，没法玩

**Comment by lowBeec** [comment]
> 在Xcode->debug->Attach to Process by ID or name里面可以进行调试PacketTunel的调试 ![picture](https://user-images.githubusercontent.com/17873903/74891944-4172eb80-53c3-11ea-9939-5322bde85cea.png)，确认一下项目内置的config是否符合你的服务端要求

请问下这个库支持shadowsocks协议吗
