### ISSUE TITLE
打包错误 缺少文件 怎么解决？

### ISSUE THREAD

**Issue by ilovebamboo** [hello-david/SwiftV2Ray#6]
![image](https://user-images.githubusercontent.com/6214084/76176084-55538580-61ea-11ea-9757-01367c27ac7a.png)

**Comment by W-MS** [comment]
先cocoapod安装framework，然后打开xcworkspace


------------------ 原始邮件 ------------------
发件人: Lotus <notifications@github.com&gt;
发送时间: 2020年3月9日 09:43
收件人: hello-david/SwiftV2Ray <SwiftV2Ray@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[hello-david/SwiftV2Ray] 打包错误 缺少文件 怎么解决？ (#6)

**Comment by ghost** [comment]
把项目根目录的Tun2socks.framework删了，然后解压Tun2socks.framework.zip应该就可以了

**Comment by Derekkaoo** [comment]
借此版一问，我将项目根目录的Tun2socks.framework删了，并解压Tun2socks.framework.zip之后，到Target PacketTunnel导入解压后的Tun2socks.framework，编译后会出现 bitcode_strip 的错误
![截圖 2020-05-13 下午5 52 28](https://user-images.githubusercontent.com/40663786/81798405-96e21300-9542-11ea-9319-7c5089cf79c4.png)

**Comment by m1faridi** [comment]
In /Users/dev-mac/Downloadse/SwiftV2Ray-master-2/Tun2socks.framework/Tun2socks(go.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/dev-mac/Downloadse/SwiftV2Ray-master-2/Tun2socks.framework/Tun2socks' for architecture arm64
