### ISSUE TITLE
xcode 各种报错 问下用的什么版本

### ISSUE THREAD

**Issue by XuCe** [hello-david/SwiftV2Ray#7]
![image](https://user-images.githubusercontent.com/4842592/76273339-96b26680-62b8-11ea-953f-2156a34ba6a6.png)

**Comment by hello-david** [comment]
😓xcode11. AppStore里面下个新的吧

qingm <notifications@github.com> 于2020年3月10日周二 上午10:19写道：

**Comment by XuCe** [comment]
好的 我之前用的10 然后不行。。我就换了12 结果还是不行。。没想到是11.。
